apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apexai.fullname" . }}-secrets
type: Opaque
stringData:
  jwt-secret: {{ .Values.env.jwt_secret | quote }}
  vault-token: {{ .Values.env.vault_token | quote }}
