"""Task tracking models (Sub-System C).

A Task is a user-facing unit of work. It can be created manually or
auto-generated by an agent run / process completing.

Status flow: todo → in_progress → review → done (or → cancelled).
"""
from __future__ import annotations

from datetime import datetime
from typing import Any
from uuid import UUID

from sqlalchemy import (
    Column,
    DateTime,
    ForeignKey,
    Index,
    String,
    Text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID as PgUUID
from sqlmodel import Field

from app.models.base import BaseModel


class Task(BaseModel, table=True):
    """User/agent-created unit of work."""

    __tablename__ = "tasks"

    org_id: str | None = Field(
        default=None,
        sa_column=Column(String(36), nullable=True, index=True),
    )
    user_id: str | None = Field(
        default=None,
        sa_column=Column(String(36), nullable=True, index=True),
        description="Creator",
    )
    assignee_id: str | None = Field(
        default=None,
        sa_column=Column(String(36), nullable=True, index=True),
        description="Current owner",
    )
    title: str = Field(sa_column=Column(String(255), nullable=False))
    description: str | None = Field(
        default=None,
        sa_column=Column(Text, nullable=True),
    )
    status: str = Field(
        default="todo",
        sa_column=Column(String(32), nullable=False, index=True),
        description="todo | in_progress | review | done | cancelled",
    )
    priority: str = Field(
        default="medium",
        sa_column=Column(String(16), nullable=False),
        description="low | medium | high | urgent",
    )
    source: str = Field(
        default="manual",
        sa_column=Column(String(32), nullable=False),
        description="manual | agent_run | process",
    )
    source_id: UUID | None = Field(
        default=None,
        sa_column=Column(PgUUID(as_uuid=True), nullable=True),
        description="FK to agent_run or process that created this",
    )
    due_at: datetime | None = Field(
        default=None,
        sa_column=Column(DateTime, nullable=True),
    )
    completed_at: datetime | None = Field(
        default=None,
        sa_column=Column(DateTime, nullable=True),
    )
    meta: dict[str, Any] = Field(
        default_factory=dict,
        sa_column=Column("metadata", JSONB, nullable=False, server_default="{}"),
    )
    parent_id: UUID | None = Field(
        default=None,
        sa_column=Column(
            PgUUID(as_uuid=True),
            ForeignKey("tasks.id", ondelete="CASCADE"),
            nullable=True,
            index=True,
        ),
        description="Parent task id (for sub-tasks)",
    )

    __table_args__ = (
        Index("ix_tasks_org_status", "org_id", "status"),
        Index("ix_tasks_assignee_status", "assignee_id", "status"),
        Index("ix_tasks_parent", "parent_id"),
    )


class TaskDependency(BaseModel, table=True):
    """Dependency edge: blocker_id must be done before blocked_id can start."""

    __tablename__ = "task_dependencies"

    blocker_id: UUID = Field(
        sa_column=Column(
            PgUUID(as_uuid=True),
            ForeignKey("tasks.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        ),
    )
    blocked_id: UUID = Field(
        sa_column=Column(
            PgUUID(as_uuid=True),
            ForeignKey("tasks.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        ),
    )
    meta: dict[str, Any] = Field(
        default_factory=dict,
        sa_column=Column("metadata", JSONB, nullable=False, server_default="{}"),
    )

    __table_args__ = (
        # blocker != blocked
        Index(
            "ix_task_dependencies_blocker_blocked",
            "blocker_id",
            "blocked_id",
            unique=True,
        ),
    )


class TaskComment(BaseModel, table=True):
    """Comment on a task."""

    __tablename__ = "task_comments"

    task_id: UUID = Field(
        sa_column=Column(
            PgUUID(as_uuid=True),
            ForeignKey("tasks.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        ),
    )
    author_id: str | None = Field(
        default=None,
        sa_column=Column(String(36), nullable=True),
    )
    author_type: str = Field(
        default="user",
        sa_column=Column(String(16), nullable=False),
        description="user | agent | system",
    )
    body: str = Field(sa_column=Column(Text, nullable=False))


class Notification(BaseModel, table=True):
    """Per-user in-app notification."""

    __tablename__ = "notifications"

    user_id: str = Field(
        sa_column=Column(String(36), nullable=False, index=True),
    )
    org_id: str | None = Field(
        default=None,
        sa_column=Column(String(36), nullable=True),
    )
    kind: str = Field(
        sa_column=Column(String(64), nullable=False, index=True),
        description="task.assigned | task.completed | agent.failed | process.paused | ...",
    )
    title: str = Field(sa_column=Column(String(255), nullable=False))
    body: str | None = Field(
        default=None,
        sa_column=Column(Text, nullable=True),
    )
    link: str | None = Field(
        default=None,
        sa_column=Column(String(512), nullable=True),
    )
    read_at: datetime | None = Field(
        default=None,
        sa_column=Column(DateTime, nullable=True),
    )

    __table_args__ = (
        Index(
            "ix_notifications_user_unread",
            "user_id",
            "read_at",
            postgresql_where=Column("read_at").is_(None),
        ),
    )