"""add failed_at to process_dlq

Revision ID: 21dfe38ac18a
Revises: 3b1889fdc702
Create Date: 2026-07-27 19:55:22.851535

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
import sqlmodel


revision: str = '21dfe38ac18a'
down_revision: Union[str, None] = '3b1889fdc702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process_dlq', sa.Column('failed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('process_dlq', 'failed_at')
    # ### end Alembic commands ###
