"""add process tables (B sub-system)

Revision ID: 3b1889fdc702
Revises: 961732273985
Create Date: 2026-07-27 19:46:44.836140

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
import sqlmodel
from sqlalchemy.dialects import postgresql

revision: str = '3b1889fdc702'
down_revision: Union[str, None] = '961732273985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_dlq',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('process_id', sa.UUID(), nullable=True),
    sa.Column('step_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_dlq_created_at'), 'process_dlq', ['created_at'], unique=False)
    op.create_index('ix_process_dlq_open', 'process_dlq', ['resolved_at'], unique=False, postgresql_where=sa.text('resolved_at IS NULL'))
    op.create_index(op.f('ix_process_dlq_process_id'), 'process_dlq', ['process_id'], unique=False)
    op.create_index(op.f('ix_process_dlq_step_id'), 'process_dlq', ['step_id'], unique=False)
    op.create_table('processes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_step', sa.String(length=64), nullable=True),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('outputs', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processes_created_at'), 'processes', ['created_at'], unique=False)
    op.create_index(op.f('ix_processes_org_id'), 'processes', ['org_id'], unique=False)
    op.create_index('ix_processes_org_status', 'processes', ['org_id', 'status'], unique=False)
    op.create_index(op.f('ix_processes_status'), 'processes', ['status'], unique=False)
    op.create_index(op.f('ix_processes_user_id'), 'processes', ['user_id'], unique=False)
    op.create_table('process_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('process_id', sa.UUID(), nullable=False),
    sa.Column('step_name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='5', nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('outputs', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('prompt_template', sa.Text(), server_default='', nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_steps_created_at'), 'process_steps', ['created_at'], unique=False)
    op.create_index(op.f('ix_process_steps_process_id'), 'process_steps', ['process_id'], unique=False)
    op.create_index(op.f('ix_process_steps_status'), 'process_steps', ['status'], unique=False)
    op.create_index('ix_process_steps_status_retry', 'process_steps', ['status', 'next_retry_at'], unique=False)
    op.create_table('process_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('process_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['process_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_events_created_at'), 'process_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_process_events_event_type'), 'process_events', ['event_type'], unique=False)
    op.create_index('ix_process_events_process_id', 'process_events', ['process_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_process_events_process_id', table_name='process_events')
    op.drop_index(op.f('ix_process_events_event_type'), table_name='process_events')
    op.drop_index(op.f('ix_process_events_created_at'), table_name='process_events')
    op.drop_table('process_events')
    op.drop_index('ix_process_steps_status_retry', table_name='process_steps')
    op.drop_index(op.f('ix_process_steps_status'), table_name='process_steps')
    op.drop_index(op.f('ix_process_steps_process_id'), table_name='process_steps')
    op.drop_index(op.f('ix_process_steps_created_at'), table_name='process_steps')
    op.drop_table('process_steps')
    op.drop_index(op.f('ix_processes_user_id'), table_name='processes')
    op.drop_index(op.f('ix_processes_status'), table_name='processes')
    op.drop_index('ix_processes_org_status', table_name='processes')
    op.drop_index(op.f('ix_processes_org_id'), table_name='processes')
    op.drop_index(op.f('ix_processes_created_at'), table_name='processes')
    op.drop_table('processes')
    op.drop_index(op.f('ix_process_dlq_step_id'), table_name='process_dlq')
    op.drop_index(op.f('ix_process_dlq_process_id'), table_name='process_dlq')
    op.drop_index('ix_process_dlq_open', table_name='process_dlq', postgresql_where=sa.text('resolved_at IS NULL'))
    op.drop_index(op.f('ix_process_dlq_created_at'), table_name='process_dlq')
    op.drop_table('process_dlq')
    # ### end Alembic commands ###
