"""add agent_todos

Revision ID: 961732273985
Revises: 3ccf6462d462
Create Date: 2026-07-26 22:24:24.738095

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
import sqlmodel


revision: str = '961732273985'
down_revision: Union[str, None] = '3ccf6462d462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_todos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_todos_agent_run_id'), 'agent_todos', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_agent_todos_created_at'), 'agent_todos', ['created_at'], unique=False)
    op.create_index('ix_agent_todos_run_seq', 'agent_todos', ['agent_run_id', 'sequence'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_todos_run_seq', table_name='agent_todos')
    op.drop_index(op.f('ix_agent_todos_created_at'), table_name='agent_todos')
    op.drop_index(op.f('ix_agent_todos_agent_run_id'), table_name='agent_todos')
    op.drop_table('agent_todos')
    # ### end Alembic commands ###
