"""add agent_runs + conversations + conversation_messages

Revision ID: b77518bfd34b
Revises: ce739057c3f8
Create Date: 2026-07-26 19:17:13.488569

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
import sqlmodel
from sqlalchemy.dialects import postgresql

revision: str = 'b77518bfd34b'
down_revision: Union[str, None] = 'ce739057c3f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('parent_run_id', sa.UUID(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('total_input_tokens', sa.Integer(), nullable=False),
    sa.Column('total_output_tokens', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_created_at'), 'conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversations_org_id'), 'conversations', ['org_id'], unique=False)
    op.create_index(op.f('ix_conversations_parent_run_id'), 'conversations', ['parent_run_id'], unique=False)
    op.create_index(op.f('ix_conversations_role'), 'conversations', ['role'], unique=False)
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_conversation_id'), 'agent_runs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_created_at'), 'agent_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_org_id'), 'agent_runs', ['org_id'], unique=False)
    op.create_index('ix_agent_runs_org_started', 'agent_runs', ['org_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_role'), 'agent_runs', ['role'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_index(op.f('ix_agent_runs_user_id'), 'agent_runs', ['user_id'], unique=False)
    op.create_index('ix_agent_runs_user_started', 'agent_runs', ['user_id', 'started_at'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), server_default='', nullable=False),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_name', sa.String(length=64), nullable=True),
    sa.Column('tool_call_id', sa.String(length=64), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('parent_message_id', sa.UUID(), nullable=True),
    sa.Column('sequence', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversation_messages_conv_sequence', 'conversation_messages', ['conversation_id', 'sequence'], unique=False)
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_created_at'), 'conversation_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversation_messages_parent_message_id'), 'conversation_messages', ['parent_message_id'], unique=False)
    op.drop_index(op.f('idx_api_keys_org_provider'), table_name='api_keys')
    op.drop_index(op.f('idx_api_keys_user_provider'), table_name='api_keys')
    op.drop_index(op.f('idx_audit_log_actor_created'), table_name='audit_log')
    op.drop_index(op.f('idx_audit_log_org_created'), table_name='audit_log')
    op.drop_index(op.f('idx_org_memberships_org_user'), table_name='org_memberships')
    op.drop_index(op.f('idx_settings_scope_key'), table_name='settings')
    op.drop_index(op.f('idx_team_memberships_team_user'), table_name='team_memberships')
    op.drop_index(op.f('idx_teams_org_slug'), table_name='teams')
    op.drop_index(op.f('idx_token_usage_org_created'), table_name='token_usage')
    op.drop_index(op.f('idx_token_usage_user_created'), table_name='token_usage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_token_usage_user_created'), 'token_usage', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_token_usage_org_created'), 'token_usage', ['org_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_teams_org_slug'), 'teams', ['org_id', 'slug'], unique=True)
    op.create_index(op.f('idx_team_memberships_team_user'), 'team_memberships', ['team_id', 'user_id'], unique=True)
    op.create_index(op.f('idx_settings_scope_key'), 'settings', ['scope', 'scope_id', 'key'], unique=True)
    op.create_index(op.f('idx_org_memberships_org_user'), 'org_memberships', ['org_id', 'user_id'], unique=True)
    op.create_index(op.f('idx_audit_log_org_created'), 'audit_log', ['org_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_audit_log_actor_created'), 'audit_log', ['actor_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_api_keys_user_provider'), 'api_keys', ['user_id', 'provider', 'is_active'], unique=False)
    op.create_index(op.f('idx_api_keys_org_provider'), 'api_keys', ['org_id', 'provider', 'is_active'], unique=False)
    op.drop_index(op.f('ix_conversation_messages_parent_message_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_created_at'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_index('ix_conversation_messages_conv_sequence', table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index('ix_agent_runs_user_started', table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_user_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_role'), table_name='agent_runs')
    op.drop_index('ix_agent_runs_org_started', table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_org_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_created_at'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_conversation_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_role'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_parent_run_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_org_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_created_at'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
